# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directories:
      - "src/Seq.Input.MSSql"
      - "src/Seq.Input.MSSql.Tests"
    schedule:
      interval: "daily"
