name: Build & Package

defaults:
  run:
    dotnet-version: '6.0.x'

on: [push]

jobs:
  build:
    runs-on: [windows-latest, x64]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ defaults.run.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ defaults.run.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
