name: Build & Package

permissions:
  contents: read

on: [ push ]

jobs:
  build:
    runs-on: [ windows-latest, x64 ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
